name: Verify

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get cache settings
        id: cache-settings
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"
          echo "::set-output name=firebase-tools::$(yarn list -s --depth=0 --pattern firebase-tools | tail -n 1 | sed 's/.*@//g')"
          
      - name: Cache Yarn Dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.cache-settings.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.node-version }}-yarn-${{ matrix.app }}-${{ hashFiles('yarn.lock') }}

      - name: Cache Firebase Emulator Binaries
        uses: actions/cache@v1
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-${{ matrix.node-version }}-firebase-${{ steps.cache-settings.outputs.firebase-tools }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Check For Lint
        run: yarn lint

      - name: Run Unit Tests + Coverage
        run: yarn test:cov

      - name: Run Build
        run: yarn build

      # Skipped since yarn isn't supported
      # - name: Size Check
      #   uses: andresz1/size-limit-action@v1.0.0
      #   env:
      #     CI_JOB_NUMBER: 1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Size Check
        run: $(yarn bin)/size-limit

      # Upload to codecov.io. Curl used in place of codecov/codecov-action
      # due to long build time. See https://github.com/codecov/codecov-action/issues/21
      - name: Upload Coverage
        run: bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
